#!/usr/bin/osascript
(*
 * ctrl - send Ctrl+key from command line, for example, to move spaces
 * Andrew Ho (andrew@zeuscat.com)
 *
 * Usage: ctrl keystroke
 *
 * Keystroke is a single letter; the script just causes the first letter
 * of its input to be output with a Ctrl key modifier. One use of this is
 * to trigger a particular Mission Control space (for example, "ctrl 1" to
 * switch to the first space).
 *
 * Example: ctrl 1
 *
 * This AppleScript requires the "Enable access for assistive devices"
 * setting to be enabled in the "Accessibility" System Preferences pane
 * in OS X pre-Mavericks. To eanble assistive UI scripting in Mavericks,
 * see this Apple KB article: http://support.apple.com/kb/HT5914
 *)

on run _argv
    set _argc to count of _argv
    if (_argc = 0)
        set result to "usage: ctrl keystroke"
    else
        set _keystroke to character 1 of item 1 of _argv
        tell application "System Events"
            keystroke _keystroke using {control down}
        end tell
    end if
end run

(*
 * Copyright (c) 2013, Andrew Ho
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 
 * 3. Neither the name of Andrew Ho nor the names of its contributors may
 *    be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *)
